version: '3.9'

services:
  scanner:
    build:
      context: .
    container_name: scanner
    ports:
      - "9000:80"
    restart: unless-stopped
    environment:
      - ENVIRONMENT=Development
      - APP_TITLE=ScannerAPI
      - APP_PREFIX=''